---
- name: Hardening and App Environment Setup
  hosts: all
  become: yes
  tasks:
    - name: Update all Ubuntu OS packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Runtime (Node.js or PHP)
      apt:
        name: ["nginx", "nodejs", "npm"]
        state: present

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
