---
- name: Hardening and App Environment Setup
  hosts: all
  become: yes
  tasks:
    - name: Update all OS packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Secure the SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

    - name: Install Runtime (Node.js or PHP)
      apt:
        name: ["nginx", "nodejs", "npm"]
        state: present

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
